# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15NQ--yi_XPWmZ1m1B2QsZgbP0SxSaUqF
"""

from google.colab import drive
drive.mount('/content/drive')

! pip install streamlit

from keras.models import load_model
import time
import tensorflow as tf
from PIL import Image
import requests
from io import BytesIO
import numpy as np

import streamlit as st
st.title("Breast Cancer Image Classification")

st.markdown("Model loaded using VGG16")

st.caption("Choose an Image")

st.file_uploader("", type = ['jpeg', 'jpg', 'png'])

model = load_model("/content/drive/MyDrive/mammography_images/mammography_images/Model/BC_diagnosis.h5")


st.subheader("Classifying.....")
with st.spinner("Wait for it...."):
    time.sleep(10)

classes = ["Benign", "Malignant"]

! streamlit run /usr/local/lib/python3.10/dist-packages/ipykernel_launcher.py



